# Generated by Django 4.1 on 2022-08-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0002_alter_preset_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
    ]
