# Generated by Django 4.1 on 2022-08-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0005_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(),
        ),
    ]
