# Generated by Django 4.1 on 2022-08-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0007_preset_count_vote_alter_preset_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preset',
            old_name='count_vote',
            new_name='sum_vote',
        ),
    ]
