# Generated by Django 4.1 on 2022-08-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0008_rename_count_vote_preset_sum_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
