# Generated by Django 4.1 on 2022-08-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0010_alter_preset_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=999),
        ),
        migrations.AlterField(
            model_name='preset',
            name='sum_vote',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(default=1),
        ),
    ]
