# Generated by Django 4.1 on 2022-08-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0012_alter_preset_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='sum_vote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
