# Generated by Django 4.1 on 2022-09-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0013_alter_preset_sum_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='files')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.AlterField(
            model_name='preset',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Описание'),
        ),
    ]
